image: maven:3.9.6-eclipse-temurin-17

variables:
  MAVEN_CLI_OPTS: "-B -Dmaven.test.failure.ignore=false"
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository
  policy: pull-push

# Reusable YAML anchors
.default_rules: &default_rules
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

.version_check: &version_check
  - echo "Using Java version: $(java -version 2>&1 | head -n 1)"
  - echo "Using Maven version: $(mvn -v | head -n 1)"

.artifacts_config: &artifacts_config
  artifacts:
    when: always
    expire_in: 1 week

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

maven:build:
  stage: build
  script:
    - *version_check
    - echo "Building application - skipping tests..."
    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS clean install -DskipTests
  <<: *artifacts_config
  artifacts:
    paths:
      - target/**
      - .m2/repository/**
  <<: *default_rules

maven:test:
  stage: test
  needs: ["maven:build"]
  script:
    - *version_check
    - echo "Running BVT tests..."
    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS clean test -DsuiteXmlFile=test-suites/testng-bvt.xml
  <<: *artifacts_config
  artifacts:
    paths:
      - target/surefire-reports/**
      - test-output/**
      - allure-results/**
  <<: *default_rules

maven:deploy:
  stage: deploy
  needs: ["maven:test"]
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  <<: *default_rules

